controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accueil:
    path: /accueil
    controller: App\Controller\HomeController::bonjour

salutation:
    path: /salutation
    controller: App\Controller\TestController::salutations

aurevoir:
    path: /redirecttoroute
    controller: App\Controller\TestController::aurevoir

redirect:
    path: /stdplus
    controller: App\Controller\TestController::redirect_

showtemplate:
    path: /showtemplate
    controller: App\Controller\TestController::showTemplate


index:
    path: /user
    controller: App\Controller\UserController::index